### ISSUE TITLE
Building view

### ISSUE THREAD

**Issue by dieterbeelaert** [oSoc14/Artoria#5] opened 2014-07-01 07:48 UTC
View + details of each building (see wireframe ...)

**Comment by coreation** [comment] 2014-07-01 08:05
Mind you that this is an open source repository, visible for everybody ( -> where is that wireframe? ). As an outstander I should be able to at least somewhat understand what the issue is all about.

**Comment by laurens-dg** [comment] 2014-07-01 14:03
Design: non existant.
Images aren't loading correctly.
But the view's there.

**Comment by laurens-dg** [comment] 2014-07-02 11:57
Images not loading was due to incorrect app permissions. That's been fixed now.

**Comment by coreation** [comment] 2014-07-02 11:59
Great! Even better would be now that you commit those changes specific to this issue and use the github referencing, that way your comments align with pushed commits. Just an FYI ;).

**Closed as completed** 2014-07-02 13:05 UTC
